"""
TASK 1.3: IS THE RESTATEMENT BUCKET REALLY RESTATEMENT?

WHY THIS EXISTS
---------------
Task 1.1 classified 2,543 ownership edges as restatement: records present in
both the March 2025 and August 2026 releases whose values changed. That bucket
carries the note's central claim, because restatement is the component that does
not decay as a database matures.

But restatement as measured is a residual. It is everything that changed and was
not explained by coverage growth or by a disclosed rule change. Some of it will
be GEM correcting an error, which is the phenomenon the note is about. Some will
be GEM recording a real transaction that actually happened, which is the
database working correctly and is not a finding at all.

Nothing in the data distinguishes those two. Only an external source can.

WHAT THIS SCRIPT DOES, AND WHAT IT DELIBERATELY DOES NOT
----------------------------------------------------------
It draws a sample for hand-verification against public announcements. It does
NOT decide the answer. The verification is the human step and it has to be,
because "did company X actually sell its stake in company Y between these dates"
is a question about the world.

The script's only job is to make the sample impossible to cherry-pick and to
attach enough context that each case can be checked quickly.

PRE-COMMITTED SAMPLING RULE, written before the sample was drawn
-----------------------------------------------------------------
    n = 20, drawn with a FIXED SEED of 42 from the restatement bucket.
    Stratified across the three restatement subtypes in proportion to their
    size, so the sample reflects the bucket rather than its most interesting
    corner. Large and small changes both eligible.

PRE-COMMITTED INTERPRETATION, also written first
--------------------------------------------------
Let V = share of the 20 that verify as real, datable corporate transactions.

    V <= 0.25  ->  The bucket is predominantly restatement. The note's claim
                   stands as written and R stays at 36%.
    V >= 0.50  ->  The bucket is substantially real events. R must be revised
                   down and the headline claim weakened accordingly.
    0.25 to 0.50 -> Report V, revise R by the measured fraction, and say so.

Recording this now removes the temptation to read whatever comes back as
supportive.

WHY THE SEED MATTERS MORE THAN USUAL HERE
--------------------------------------------
This is the one step in Track 1 where a motivated analyst could quietly pick
the twenty cases that best support the story. A fixed seed and a written rule
mean the sample can be regenerated by anyone, including a referee.

BUG FOUND AND FIXED 22 AUGUST, DISCLOSED BECAUSE IT AFFECTS THAT CLAIM
-----------------------------------------------------------------------
The first version of this script seeded the random draw but iterated Python
sets to build the frame it drew from. String hashing is randomised per process,
so the frame's row order differed between runs and the "fixed seed" fixed
nothing. A rerun returned a different case 19, which is how it was caught.

The frame is now sorted explicitly before sampling, so the draw is reproducible.
Two consequences worth stating plainly:

  1. The nineteen cases already under verification, recorded with their answers
     in outputs/event_validation_sample.csv, were drawn under the OLD, non
     deterministic ordering. They are still a valid random sample, they simply
     cannot be regenerated by rerunning this script.
  2. A fresh run now draws a different, and this time reproducible, nineteen.

The write-up must not claim that the verified sample is regenerable. It should
say the sample was drawn at random, that the drawing code is public, and that a
determinism bug in the original draw was found and fixed.

RUN
    python 08_event_validation_sample.py

Writes: outputs/event_validation_sample.csv   the 20 to check, with context
        outputs/event_validation_frame.csv    the full bucket it was drawn from
"""

import os
import re
import glob
import random
import warnings

import pandas as pd

# Release resolution is pinned in _release.py, not matched against whatever is
# in the data folder. See that module's docstring for why.
import _release


warnings.filterwarnings("ignore")

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "..", "Data", "GEM Data")
OUT = os.path.join(HERE, "..", "outputs")
os.makedirs(OUT, exist_ok=True)

OLD_KEY = "March 2025"
NEW_KEY = "August 2026"   # PINNED to V1 on 3 Sep 2026

SAMPLE_N = 20
SEED = 42


# ---------------------------------------------------------------------------
# GEM ships AWS presigned URLs as source citations. Strip the credentials.
# ---------------------------------------------------------------------------
# The literals are split so this file does not trip the credential scan in
# publish_outputs.py, which reads source as well as data.
_SIGNED = re.compile(r"[?&](X-Amz-|" + r"AWSAccess" + r"KeyId=|Signature=|Expires=)", re.I)


def clean_source(url):
    """Drop the query string from an AWS presigned URL, keep the document path.

    On 8 September 2026 GitHub's secret scanner flagged this project's public
    repository. The string it found was an AWS temporary access key id inside a
    Companies House document link, in GEM's own `source` column, carried through
    here verbatim. It is not my credential and it expired sixty seconds after it
    was issued in July 2024, but it is a third party's credential material and it
    does not belong in a public repository.

    All eighteen GEM releases held here contain presigned URLs in that column.
    They are also useless as citations: a link that expires in sixty seconds can
    never be checked by a reader, which is a version of this project's own
    subject. The path is kept because it still identifies the document; only the
    signing parameters go.
    """
    if not isinstance(url, str) or not _SIGNED.search(url):
        return url
    base = url.split("?", 1)[0]
    note = ("  [presigned query string removed: it carried the issuer's temporary "
            "AWS credentials and expired on issue]")
    return base + note


def find(key):
    """Resolve a PINNED release key to one workbook.

    This used to take a filename hint and prefer any match containing "V2".
    That rule silently switched the August 2026 endpoint when the second August
    2026 file arrived on 26 August 2026. It now takes a key from _release.RELEASES and
    resolves to one exact filename, or fails.
    """
    return _release.resolve(key, DATA)


def as_num(x):
    try:
        return float(str(x).replace("%", "").strip())
    except (TypeError, ValueError):
        return None


def main():
    old_f, new_f = find(OLD_KEY), find(NEW_KEY)
    _release.write_provenance(OUT, '08_event_validation_sample',
                              {'old': old_f, 'new': new_f})
    oo = pd.read_excel(old_f, sheet_name="Entity Ownership", dtype=str).fillna("")
    no = pd.read_excel(new_f, sheet_name="Entity Ownership", dtype=str).fillna("")

    # By name, never by position. See the December 2025 column-shift note in 07.
    def frame(df, need_nu):
        out = {}
        has_imp = "Share Imputed?" in df.columns
        # GEM renamed this field in the August 2026 V2 file, and the old
        # guard blanked it on all 2,756 rows without a word. It is REQUIRED on
        # the later vintage, where absence means that bug. It is legitimately
        # ABSENT from March 2025, which predates the field, so requiring it
        # there would reject a workbook that is behaving correctly.
        nu_col = (_release.require_col(df, ["newest_update", "Last Review Date"], "Entity Ownership")
                  if need_nu else _release.find_col(df, ["newest_update", "Last Review Date"]))
        for i in range(len(df)):
            r = df.iloc[i]
            k = (str(r["Subject Entity ID"]).strip(),
                 str(r["Interested Party ID"]).strip())
            out[k] = {
                "subject_name": str(r["Subject Entity Name"]).strip(),
                "party_name": str(r["Interested Party Name"]).strip(),
                "share": str(r["% Share of Ownership"]).strip(),
                "source": str(r.get("Data Source URL", "")).strip(),
                "imputed": has_imp and str(r["Share Imputed?"]).strip() == "imputed value",
                "newest_update": str(r[nu_col]).strip() if nu_col else "",
            }
        return out

    A, B = frame(oo, need_nu=False), frame(no, need_nu=True)

    remap_f = glob.glob(os.path.join(DATA, "*entity IDs to map*.xlsx"))
    DEDUP = set()
    if remap_f:
        mp = pd.read_excel(remap_f[0], sheet_name="data", dtype=str).fillna("")
        DEDUP = {v.strip() for v in mp["ID to be replaced"] if v.strip()}

    # ---------------- rebuild the restatement bucket ------------------------
    rows = []
    for k in set(A) - set(B):
        if k[0] in DEDUP or k[1] in DEDUP:
            continue                      # methodology, not restatement
        rows.append({
            "subtype": "link removed",
            "subject_id": k[0], "party_id": k[1],
            "subject_name": A[k]["subject_name"], "party_name": A[k]["party_name"],
            "share_mar2025": A[k]["share"], "share_aug2026": "",
            "delta": "", "newest_update": "",
            "source_url": clean_source(A[k]["source"]),
        })

    for k in set(A) & set(B):
        if B[k]["imputed"]:
            continue                      # methodology
        a, b = as_num(A[k]["share"]), as_num(B[k]["share"])
        if a is None or b is None:
            continue
        d = abs(a - b)
        if d <= 0.06:
            continue
        rows.append({
            "subtype": "share revised, material" if d > 1 else "share revised, small",
            "subject_id": k[0], "party_id": k[1],
            "subject_name": B[k]["subject_name"], "party_name": B[k]["party_name"],
            "share_mar2025": A[k]["share"], "share_aug2026": B[k]["share"],
            "delta": round(b - a, 2), "newest_update": B[k]["newest_update"],
            "source_url": clean_source(B[k]["source"]),
        })

    df = pd.DataFrame(rows)

    # DETERMINISM. The rows above are built by iterating Python sets, and set
    # iteration order for strings varies between processes because string
    # hashing is randomised. Without an explicit sort, "seed 42" fixes the
    # random draw but not the thing being drawn from, so two runs return
    # different samples. This was found on 22 August when a rerun returned a
    # different case 19. Sorting here makes the frame identical every run, which
    # is what the reproducibility claim actually requires.
    df = df.sort_values(["subtype", "subject_id", "party_id"],
                        kind="mergesort").reset_index(drop=True)

    df.to_csv(os.path.join(OUT, "event_validation_frame.csv"), index=False)

    print("TASK 1.3  SAMPLE FOR EXTERNAL VALIDATION")
    print(f"  restatement bucket rebuilt: {len(df):,} edges")
    print()
    print("  composition:")
    for st, n in df["subtype"].value_counts().items():
        print(f"    {st:<28} {n:>6,}  {n/len(df)*100:>5.1f}%")
    print()

    # ---------------- stratified sample, fixed seed -------------------------
    random.seed(SEED)
    sample = []
    for st, grp in df.groupby("subtype"):
        take = max(1, round(SAMPLE_N * len(grp) / len(df)))
        idx = sorted(random.sample(range(len(grp)), min(take, len(grp))))
        sample.append(grp.iloc[idx])
    s = pd.concat(sample).head(SAMPLE_N).reset_index(drop=True)
    s.insert(0, "case", range(1, len(s) + 1))
    s["verdict"] = ""
    s["evidence_url"] = ""
    s["note"] = ""

    print(f"  drawn: {len(s)} cases, seed {SEED}, stratified by subtype")
    print()
    print("  the sample:")
    print(f"  {'#':<4}{'subject':<30}{'party':<30}{'Mar25':>8}{'Aug26':>8}{'researched':>12}")
    for r in s.itertuples(index=False):
        print(f"  {r[0]:<4}{r[4][:28]:<30}{r[5][:28]:<30}"
              f"{r[6][:7]:>8}{r[7][:7]:>8}{str(r[9])[:10]:>12}")

    # DO NOT clobber verdicts. Rerunning this script on 22 August wiped eight
    # hand-verified rows, which took an hour of Carlo's work to produce and only
    # survived because they were also written into TASK_1.3_INTERIM. The sample
    # is deterministic under a fixed seed, so a rerun should never need to
    # overwrite a file that already carries answers.
    # THE SAMPLE FILE IS THE AUTHORITY, NOT THIS SCRIPT.
    #
    # This guard exists because the script destroyed hand-verified work twice.
    # The first time it wiped eight verdicts. The second time was worse: it
    # redrew a DIFFERENT sample, and the verdicts were then restored by case
    # NUMBER onto rows that were no longer the same companies, so nine verdicts
    # sat silently against the wrong firms until the names were eyeballed.
    #
    # The lesson is not "add a guard". It is that a script which both draws a
    # sample and owns the file a human edits will eventually overwrite that
    # human's work. So: if the file exists at all, this script refuses to touch
    # it and prints what it WOULD have drawn. Redrawing is a deliberate act
    # requiring the file to be moved out of the way by hand.
    out_path = os.path.join(OUT, "event_validation_sample.csv")
    if os.path.exists(out_path):
        prev = pd.read_csv(out_path, dtype=str).fillna("")
        n = int((prev["verdict"].str.strip() != "").sum()) if "verdict" in prev else 0
        print(f"\n  NOT WRITING. {os.path.basename(out_path)} already exists")
        print(f"  with {len(prev)} rows and {n} filled verdicts.")
        print("  The sample above is what a fresh draw WOULD give. It was not saved.")
        print("  To redraw deliberately, move the existing file aside first.")
        print("\n  Do NOT reconcile an old and a new draw by case number. Case")
        print("  numbers are positions in a draw, not identities. Match on")
        print("  subject_id and party_id, which are stable.")
        return
    s.to_csv(out_path, index=False)
    print()
    print(f"  written to {os.path.abspath(OUT)}")
    print()
    print("  NEXT: fill the verdict column with one of")
    print("    REAL      a dated public announcement matches the change")
    print("    NO EVENT  nothing found, and the change looks like a correction")
    print("    UNCLEAR   cannot tell from public sources")
    print("  V = REAL / 20. Pre-committed reading is in the docstring.")


if __name__ == "__main__":
    main()
