"""
RENDER THE MEASUREMENT NOTE TO PDF.

The note is generated by 19_build_note.py, so its PDF must be generated too.
Nothing here edits content: it injects a print stylesheet and prints the page
with headless Chromium, so the PDF and the HTML cannot say different things.

Run:  python3 note_to_pdf.py <note.html> <out.pdf>
"""
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

CHROME_CANDIDATES = [
    "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
    "/Applications/Chromium.app/Contents/MacOS/Chromium",
    "/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge",
    "google-chrome",
    "chromium",
]

PRINT_CSS = """
@page { size: A4; margin: 20mm 18mm 18mm 18mm; }
@page :first { margin-top: 16mm; }
html { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
body { background: #fff !important; font-size: 10.5pt; line-height: 1.5; }
.wrap { max-width: none; margin: 0; padding: 0; }
h1 { font-size: 19pt; }
.sub { font-size: 11pt; }
.meta { font-size: 8.5pt; margin-bottom: 20px; }
h2 { font-size: 13pt; margin: 22px 0 8px; padding-top: 12px;
     break-after: avoid; page-break-after: avoid; }
h3 { font-size: 11pt; margin: 15px 0 6px;
     break-after: avoid; page-break-after: avoid; }
p, li { orphans: 3; widows: 3; }
table { font-size: 8.5pt; margin: 11px 0 14px;
        break-inside: avoid; page-break-inside: avoid; }
th, td { padding: 4px 7px; }
thead { display: table-header-group; }
tr { break-inside: avoid; page-break-inside: avoid; }
.summary { break-inside: avoid; page-break-inside: avoid;
           padding: 14px 16px; margin-bottom: 20px; }
.note { break-inside: avoid; page-break-inside: avoid; font-size: 9.5pt; padding: 9px 12px; }
.src { font-size: 8pt; margin: -8px 0 14px; }
.appendix { break-before: page; page-break-before: always;
            margin-top: 0; padding-top: 0; border-top: none; }
.appendix h2 { border-top: none; padding-top: 0; margin-top: 0; }
code { font-size: 8.5pt; }
footer { break-inside: avoid; page-break-inside: avoid; font-size: 8.5pt; }
"""


def find_chrome():
    for c in CHROME_CANDIDATES:
        p = c if os.path.isabs(c) else shutil.which(c)
        if p and os.path.exists(p):
            return p
    return None


def render(src: Path, out: Path) -> None:
    src = src.resolve()
    out = out.resolve()
    html = src.read_text(encoding="utf-8")
    if "</style>" not in html:
        sys.exit("ABORTED: no <style> block found, so the print rules have nowhere to go")
    html = html.replace("</style>", PRINT_CSS + "\n</style>", 1)

    staged = Path(tempfile.mkdtemp()) / "note_print.html"
    staged.write_text(html, encoding="utf-8")

    chrome = find_chrome()
    if chrome:
        subprocess.run(
            [chrome, "--headless", "--disable-gpu", "--no-pdf-header-footer",
             f"--print-to-pdf={out}", staged.as_uri()],
            check=True, capture_output=True,
        )
        return

    try:
        import asyncio
        from playwright.async_api import async_playwright
    except ImportError:
        sys.exit("ABORTED: no Chrome, Chromium or Edge found, and playwright is not installed.")

    async def go():
        async with async_playwright() as p:
            browser = await p.chromium.launch()
            page = await browser.new_page()
            await page.goto(staged.as_uri(), wait_until="networkidle")
            await page.pdf(path=str(out), format="A4", print_background=True,
                           margin={"top": "16mm", "bottom": "16mm",
                                   "left": "18mm", "right": "18mm"})
            await browser.close()

    asyncio.run(go())


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    render(Path(sys.argv[1]), Path(sys.argv[2]))
